<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<!-- Set CopyToOutputDirectory for a specific DLL in the package -->
		<Content Include="$(MSBuildThisFileDirectory)..\runtimes\win10-$(Platform)\lib\net9.0\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="$(MSBuildThisFileDirectory)..\runtimes\win10-$(Platform)\native\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<PropertyGroup>
		<!-- Set the target framework for the package -->
		<TargetFramework>net9.0-windows</TargetFramework>
		<!-- Set the platform for the package -->
		<Platform>$(Platform)</Platform>
		<PackageId>GuardianConnectSDK</PackageId>
	</PropertyGroup>
</Project>
