<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>

        <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64;ARM64</Platforms>

        <AssemblyOriginatorKeyFile>TimDevStrongKeyNameFile.snk</AssemblyOriginatorKeyFile>
        <PublicSign>false</PublicSign>
        <AssemblyName>GuardianFirewallService</AssemblyName>
        <AssemblyVersion>0.10.1.52</AssemblyVersion>
        <FileVersion>0.10.1.52</FileVersion>

        <ApplicationIcon>Guardian.ico</ApplicationIcon>

        <OutputType>Exe</OutputType>

    </PropertyGroup>
    <ItemGroup>
        <Using Include="System.Runtime.Serialization " />
        <Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.3" />
        <PackageReference Include="Microsoft.Win32.SystemEvents" Version="9.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Serilog.Enrichers.CallerInfo" Version="1.0.5" />
        <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Enrichers.WithCaller" Version="1.3.0" />
        <PackageReference Include="Serilog.Settings.AppSettings" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
        <PackageReference Include="System.Threading.AccessControl" Version="9.0.3" />
    </ItemGroup>
    <ItemGroup>
      <MauiAsset Include="logsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </MauiAsset>
    </ItemGroup>
    <ItemGroup>
      <None Update="appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="installassvc.cmd">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="logsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="NecessaryInstallPackages\dotnet-hosting-8.0.2-win.exe">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="NecessaryInstallPackages\dotnet-runtime-8.0.7-win-arm64.exe">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="NecessaryInstallPackages\dotnet-runtime-8.0.7-win-x64.exe">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="NecessaryInstallPackages\VC_redist.arm64.exe">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="NecessaryInstallPackages\VC_redist.x64.exe">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="uninstallfromservices.cmd">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Guardian.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
      <AvaloniaResource Include="Guardian.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\GuardianConnect\GuardianConnect.csproj" />
      <ProjectReference Include="..\NativeRoutines\NativeRoutines.vcxproj" />
      <ProjectReference Include="..\Shared\GuardianConnect.Shared.csproj" />
    </ItemGroup>
    <!--
    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="C:\GitHub\Guardian\GuardianConnect-Win-PoC\GuardianWinService\bin\uninstallsvc.cmd" />
    </Target>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="C:\GitHub\Guardian\GuardianConnect-Win-PoC\GuardianWinService\bin\installdbgsvc.cmd" />
    </Target>
    -->

</Project>