<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
		<tags>GuardianFirewallService</tags>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Configurations>Debug;Release</Configurations>
        <Platforms>x64;ARM64</Platforms>
        <!--
	    <PublishAot>true</PublishAot>
        -->
		<!--
		<OutDir>..\BuildOutput\$(MSBuildProjectName)\runtimes\$(Platform)\</OutDir>
        -->

        <AssemblyOriginatorKeyFile>TimDevStrongKeyNameFile.snk</AssemblyOriginatorKeyFile>
        <PublicSign>false</PublicSign>
        <AssemblyName>GuardianFirewallService</AssemblyName>

        <ApplicationIcon>Guardian.ico</ApplicationIcon>

        <OutputType>Exe</OutputType>

    </PropertyGroup>
    <ItemGroup>
        <Using Include="System.Runtime.Serialization " />
        <Using Include="Microsoft.Extensions.DependencyInjection.Extensions" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.3" />
        <PackageReference Include="Microsoft.Win32.SystemEvents" Version="9.0.3" />
        <PackageReference Include="System.Management" Version="9.0.8" />
        <PackageReference Include="System.Threading.AccessControl" Version="9.0.3" />
    </ItemGroup>
	<!--
    <ItemGroup>
      <MauiAsset Include="logsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </MauiAsset>
    </ItemGroup>
      -->
    <ItemGroup>
      <None Update="appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="installassvc.cmd">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="logsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="uninstallfromservices.cmd">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Guardian.ico">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
      <AvaloniaResource Include="Guardian.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\GuardianConnect\GuardianConnect.csproj" />
      <ProjectReference Include="..\Shared\GuardianConnect.Shared.csproj" />
      <ProjectReference Include="..\Win32Calls\Win32Calls.csproj" />
    </ItemGroup>
    <!--
    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
      <Exec Command="C:\GitHub\Guardian\GuardianConnect-Win-PoC\GuardianWinService\bin\uninstallsvc.cmd" />
    </Target>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="C:\GitHub\Guardian\GuardianConnect-Win-PoC\GuardianWinService\bin\installdbgsvc.cmd" />
    </Target>
    -->

</Project>