<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>GuardianConnect SDK Shared Libraries</Title>
        <Authors>Guardian Group of DNSFilter, Inc.</Authors>
        <Copyright>DNSFilter, Inc.</Copyright>
        <PackageIcon>Guardian.ico</PackageIcon>
        <tags>GuardianConnectSDK</tags>
        <Platforms>x64;ARM64</Platforms>
        <!--
        <GenerateReferenceAssembly>true</GenerateReferenceAssembly>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <Deterministic>true</Deterministic>
        -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Win32.SystemEvents" Version="10.0.10" />
        <PackageReference Include="Serilog" Version="4.3.0"/>
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1"/>
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0"/>
        <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0"/>
        <PackageReference Include="Serilog.Enrichers.WithCaller" Version="1.3.0"/>
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0"/>
        <PackageReference Include="Serilog.Settings.AppSettings" Version="3.0.0"/>
        <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0"/>
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Guardian.ico">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>
