<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>GuardianConnect SDK Shared Libraries</Title>
        <Authors>Guardian Group of DNSFilter, Inc.</Authors>
        <Copyright>DNSFilter, Inc.</Copyright>
        <PackageIcon>Guardian.ico</PackageIcon>
		<tags>GuardianConnectSDK</tags>
		<Platforms>x64;ARM64</Platforms>
        <!--
        <GenerateReferenceAssembly>true</GenerateReferenceAssembly>
        <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
        <Deterministic>true</Deterministic>
        -->
    </PropertyGroup>

    <ItemGroup>
      <None Update="Guardian.ico">
        <Pack>True</Pack>
        <PackagePath></PackagePath>
      </None>
    </ItemGroup>

</Project>
