
name: Dual Platform GuardianConnectSDK build and package

on:
  workflow_dispatch:
    branches: [ "*" ]
    
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: .\GuardianConnectSDK
    
jobs:

  build-both-architectures:

    strategy:
      matrix:
        configuration: [Release]
          
    runs-on: windows-2022

    env:
      Solution_Name: GuardianConnectSDK.sln
      unsignedzipfile: "UnsignedGuardianBinaries.zip"
      signedzipfile: "SignedGuardianBinaries.zip"

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get a dir
      run: dir
      shell: cmd

    # Get CPU Architecture from Github variable
    - name: Get CPU from GH's $RUNNER_ARCH
      run: |
          $cpu = $env:RUNNER_ARCH.replace('X', 'x').replace('ARM', 'arm')
          echo "CPU=$cpu" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    # Show env
    - name: Show env after above with colon syntax
      run: echo "$env:CPU"

    - name: Extract Version and set as env var
      shell: pwsh
      run: |
            $version = Select-String '<Version>(.+?)</Version>' Directory.Build.Props | % { $_.Matches[0].Groups[1].Value }
            "PKGVERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Use the extracted value
      run: |
        echo "PKGVERSION="${{ env.PKGVERSION }}

    - name: Create GuardianConnectSDK_NugetPackages folder
      shell: cmd
      run: md ..\GuardianConnectSDK_NugetPackages

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Build GuardianConnect for x64 CPU
      run: msbuild /t:restore /t:Build /p:Platform=x64 /p:Configuration=Release /p:RuntimeIdentifier=win-x64 GuardianConnect\GuardianConnect.csproj

    - name: Build GuardianConnect for ARM64 CPU
      run: msbuild /t:restore /t:Build /p:Platform=arm64 /p:Configuration=Release /p:RuntimeIdentifier=win-arm64 GuardianConnect\GuardianConnect.csproj
    
    - name: Build GuardianConnect.Services for x64 CPU
      run: msbuild /t:restore /t:Build /p:Platform=x64 /p:Configuration=Release /p:RuntimeIdentifier=win-x64 GuardianConnect.Services\GuardianConnect.Services.csproj
      
    - name: Build GuardianConnect.Services for ARM64 CPU
      run: msbuild /t:restore /t:Build /p:Platform=arm64 /p:Configuration=Release /p:RuntimeIdentifier=win-arm64 GuardianConnect.Services\GuardianConnect.Services.csproj
      
    - name: Build GuardianConnectSDK.Services.Abstractions for any CPU
      run: msbuild /t:restore /t:Build /p:Configuration=Release GuardianConnect.Abstractions\GuardianConnect.Abstractions.csproj
      
####    - name: Build GuardianFirewall Service for x64 CPU
####      run: |
####            msbuild /t:restore /t:Build /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=0 /p:RuntimeIdentifier=win-x64 GuardianFirewallService\GuardianFirewallService.csproj
####            msbuild /t:Publish /p:PublishReadyToRun=false /p:IncludeNativeLibrariesForSelfExtract=false /p:IncludeAllContentForSelfExtract=false /p:Configuration=Release /p:Platform=x64 /p:WarningLevel=0 /p:RuntimeIdentifier=win-x64 GuardianFirewallService\GuardianFirewallService.csproj
####
####    - name: Build GuardianFirewall Service for arm64 CPU
####      run: |
####        msbuild /t:restore /t:Build /p:Configuration=Release /p:Platform=arm64 /p:WarningLevel=0 /p:RuntimeIdentifier=win-arm64 GuardianFirewallService\GuardianFirewallService.csproj
####        msbuild /t:Publish /p:PublishReadyToRun=false /p:IncludeNativeLibrariesForSelfExtract=false /p:IncludeAllContentForSelfExtract=false /p:Configuration=Release /p:Platform=arm64 /p:WarningLevel=0 /p:RuntimeIdentifier=win-arm64 GuardianFirewallService\GuardianFirewallService.csproj
      
     # Zip up our binaries for specific zip signing in SignPath
    - name: Zip Guardian binaries for SignPath deep-signing
      shell: cmd
      run: 7z a -bb3 "${{env.unsignedzipfile}}" @ListOfGuardianConnectSDKFilesToSign.fls

    - name: Get a dir of zip
      run: dir
      shell: cmd

    - name: Upload build artifacts - include Service SDKs - x64 first- UNSIGNED SO WE CAN GIVE AS SAMPLE TO SIGNPATH
      uses: actions/upload-artifact@v4
      with:
        name: UnsignedGuardianBinaries.zip
        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\${{env.unsignedzipfile}}

      # Sign Guardian binaries only  with certificate
    - name: Sign Guardian Binaries with certificate
      run: Install-Module -Name SignPath -Force
        
        Submit-SigningRequest `
        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
        -ProjectSlug "Guardian" `
        -SigningPolicySlug "Guardian_DNSF_Branded" `
        -ArtifactConfigurationSlug  "NoCPP_SDK_and_SDK_SVC" `
        -InputArtifactPath "${{ env.unsignedzipfile }}" `
        -OutputArtifactPath "${{ env.signedzipfile }}" `
        -WaitForCompletion
      
      # Unzip what has just been signed
    - name: Unzip the newly-created file to list Guardian binaries for SignPath deep-signing
      run: 7z x -aoa -bb3 "${{ env.signedzipfile }}"

    - name: Create GuardianConnectSDK_x64.nupkg package bundle for EACH CPU build - x64 first
      run: nuget pack GuardianConnectSDK_x64.nuspec -Version ${{env.PKGVERSION}}
      shell: cmd

    - name: Create GuardianConnectSDK_ARM64.nupkg package bundle for EACH CPU build - then ARM64
      run: nuget pack GuardianConnectSDK_ARM64.nuspec -Version ${{env.PKGVERSION}}
      shell: cmd

    - name: Create GuardianConnect.Services.SDK_x64.nupkg package bundle for EACH CPU build - x64 first
      if: github.ref_name == 'main'
      run: nuget pack GuardianConnect.Services.SDK_x64.nuspec -Version ${{env.PKGVERSION}}.1
      shell: cmd
      
    - name: Create GuardianConnect.Services.SDK_arm64.nupkg package bundle for EACH CPU build - arm64 first
      if: github.ref_name == 'main'
      run: nuget pack GuardianConnect.Services.SDK_arm64.nuspec -Version ${{env.PKGVERSION}}.1
      shell: cmd

    - name: Create GuardianConnectSDK.Services.Abstractions.nupkg package bundle
      if: github.ref_name == 'main'
      run: nuget pack GuardianConnectSDK.Services.Abstractions.nuspec -Version ${{env.PKGVERSION}}.2
      shell: cmd

#    - name: Upload build artifacts - both Service SDKs - x64 first- UNSIGNED SO WE CAN GIVE AS SAMPLE TO SIGNPATH
#      uses: actions/upload-artifact@v4
#      with:
#        name: "GuardianConnect.Services.SDK_x64.${{env.PKGVERSION}}.nupkg"
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\GuardianConnect.Services.SDK_x64.${{env.PKGVERSION}}.nupkg
#    
#    - name: Upload build artifacts - both Service SDKs - arm64 - UNSIGNED SO WE CAN GIVE AS SAMPLE TO SIGNPATH
#      uses: actions/upload-artifact@v4
#      with:
#        name: "GuardianConnect.Services.SDK_arm64.${{env.PKGVERSION}}.nupkg"
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\GuardianConnect.Services.SDK_arm64.${{env.PKGVERSION}}.nupkg
#        
#    - name: Upload build artifacts - both SDKs - x64 first- UNSIGNED SO WE CAN GIVE AS SAMPLE TO SIGNPATH
#      uses: actions/upload-artifact@v4
#      with:
#        name: "GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg"
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg
#
#    - name: Upload build artifacts - both SDKs - now ARM64 - UNSIGNED SO WE CAN GIVE AS SAMPLE TO SIGNPATH
#      uses: actions/upload-artifact@v4
#      with:
#        name: "GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg"
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg

      # Sign GuardianConnectSDK x64 package with certificate
      # Name GuardianConnectSDK<Platform> Nuget Package
      # Slug GuardianConnectSDK_<Platform>_Nuget_Package
    - name: Sign GuardianConnectSDK_x64 package with certificate
      run: Install-Module -Name SignPath -Force

        Submit-SigningRequest `
        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
        -ProjectSlug "Guardian" `
        -SigningPolicySlug "Guardian_DNSF_Branded" `
        -ArtifactConfigurationSlug GuardianConnectSDK_x64_Nuget_Package `
        -InputArtifactPath "GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg" `
        -OutputArtifactPath "SIGNED_GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg"  `
        -WaitForCompletion
      
    # Sign GuardianConnectSDK ARM64 package with certificate
    # Name GuardianConnectSDK ARM64 Nuget Package
    # Slug GuardianConnectSDK_ARM64_Nuget_Package
    - name: Sign GuardianConnectSDK_ARM64 package with certificate
      run: Install-Module -Name SignPath -Force

        Submit-SigningRequest `
        -InputArtifactPath "GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg" `
        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
        -ProjectSlug "Guardian" `
        -SigningPolicySlug "Guardian_DNSF_Branded" `
        -OutputArtifactPath "SIGNED_GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg"  `
        -ArtifactConfigurationSlug GuardianConnectSDK_ARM64_Nuget_Package `
        -WaitForCompletion

    - name: Sign GuardianConnectServicesSDK_x64 package with certificate
      run: Install-Module -Name SignPath -Force

        Submit-SigningRequest `
        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
        -ProjectSlug "Guardian" `
        -SigningPolicySlug "Guardian_DNSF_Branded" `
        -ArtifactConfigurationSlug GuardianConnectServiceSDK_X64 `
        -InputArtifactPath "GuardianConnect_Services_SDK_x64.${{env.PKGVERSION}}.1.nupkg" `
        -OutputArtifactPath "SIGNED_GuardianConnect_Services_SDK_x64.${{env.PKGVERSION}}.1.nupkg"  `
        -WaitForCompletion

    - name: Sign GuardianConnectServicesSDK_arm64 package with certificate
      run: Install-Module -Name SignPath -Force

        Submit-SigningRequest `
        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
        -ProjectSlug "Guardian" `
        -SigningPolicySlug "Guardian_DNSF_Branded" `
        -ArtifactConfigurationSlug GuardianConnectServicesSDK_ARM64 `
        -InputArtifactPath "GuardianConnect_Services_SDK_arm64.${{env.PKGVERSION}}.1.nupkg" `
        -OutputArtifactPath "SIGNED_GuardianConnect_Services_SDK_arm64.${{env.PKGVERSION}}.1.nupkg"  `
        -WaitForCompletion
    
      # Sign GuardianFirewallService package with certificate
    # Name GuardianFirewallService Windows Nuget Package
    # Slug GuardianConnectSDK_Windows_Nuget_Package
####    - name: Sign GuardianFirewallService package with certificate
####      run: Install-Module -Name SignPath -Force
####        
####        Submit-SigningRequest `
####        -InputArtifactPath "GuardianFirewallService.${{env.PKGVERSION}}.nupkg" `
####        -ApiToken "${{ secrets.CI_SIGNPATH_USER_TOKEN }}" `
####        -OrganizationId "5c1e4170-8bf7-48b1-8542-78374ccc3471" `
####        -ProjectSlug "Guardian" `
####        -SigningPolicySlug "Guardian_DNSF_Branded" `
####        -OutputArtifactPath "SIGNED_GuardianFirewallService.${{env.PKGVERSION}}.nupkg" `
####        -ArtifactConfigurationSlug GuardianFirewallService_Nuget_Package `
####        -WaitForCompletion
      
      # Upload the nuget packages: (https://github.com/marketplace/actions/upload-a-build-artifact)
#    - name: Upload build artifacts - GuardianConnectSDK_x64
#      uses: actions/upload-artifact@v4
#      with:
#        name: SIGNED_GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\SIGNED_GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg
#
#    - name: Upload build artifacts - GuardianConnectSDK_ARM64
#      uses: actions/upload-artifact@v4
#      with:
#        name: SIGNED_GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg
#        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\SIGNED_GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg
        
    - name: Upload build artifacts - GuardianConnect.Services.SDK_x64
      uses: actions/upload-artifact@v4
      with:
        name: SIGNED_GuardianConnectServicesSDK_x64.${{env.PKGVERSION}}.nupkg
        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\SIGNED_GuardianConnect_Services_SDK_x64.${{env.PKGVERSION}}.1.nupkg

    - name: Upload build artifacts - GuardianConnect.Services.SDK_ARM64
      uses: actions/upload-artifact@v4
      with:
        name: SIGNED_GuardianConnectServicesSDK_ARM64.${{env.PKGVERSION}}.nupkg
        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\SIGNED_GuardianConnect_Services_SDK_ARM64.${{env.PKGVERSION}}.1.nupkg
        
        ####    - name: Upload build artifacts - GuardianFirewall Service
####      uses: actions/upload-artifact@v4
####      with:
####        name: SIGNED_GuardianFirewallService.${{env.PKGVERSION}}.nupkg 
####        path: D:\a\GuardianConnect-Windows\GuardianConnect-Windows\GuardianConnectSDK\SIGNED_GuardianFirewallService.${{env.PKGVERSION}}.nupkg 
        
        
        # Add github as source for nuget
    - name: Add GitHub as nuget package source
      shell: cmd
      run: dotnet nuget add source --username time4dnsf --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GuardianFirewall/index.json"
        
    # Update GitHub Packages with these nuget packages
    - name: Update GitHub with nuget packages - SDK x64
      if: github.ref_name == 'main'
      run: nuget push SIGNED_GuardianConnectSDK_x64.${{env.PKGVERSION}}.nupkg `${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub -SkipDuplicate
    - name: Update GitHub with nuget packages - SDK ARM64
      if: github.ref_name == 'main'
      run: nuget push SIGNED_GuardianConnectSDK_ARM64.${{env.PKGVERSION}}.nupkg `${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub -SkipDuplicate
      
    # Update GitHub Packages for Connect.Services with these nuget packages
    - name: Update GitHub with nuget packages - SDK Services x64
      if: github.ref_name == 'main'
      run: nuget push SIGNED_GuardianConnect_Services_SDK_x64.${{env.PKGVERSION}}.1.nupkg `${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub
      
    - name: Update GitHub with nuget packages - SDK Services ARM64
      if: github.ref_name == 'main'
      run: nuget push SIGNED_GuardianConnect_Services_SDK_ARM64.${{env.PKGVERSION}}.1.nupkg `${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub
      
    # Update GitHub Packages for ConnectSDK.Services.Abstractions with nuget package
    - name: Update GitHub with nuget packages - SDK Services Abstractions
      if: github.ref_name == 'main'
      run: nuget push GuardianConnectSDK_Services_Abstractions.${{env.PKGVERSION}}.2.nupkg `${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub
      
####    - name: Update GitHub with nuget packages - Service
####      run: nuget push SIGNED_GuardianFirewallService.${{env.PKGVERSION}}.nupkg ${{ secrets.GUARDIANFIREWALL_GH_PKG_TOKEN }} -Source GitHub -SkipDuplicate
